### ISSUE TITLE
Unable to open monitor interface

### ISSUE THREAD

**Issue by m33ts4k0z** [neofeo/BOX86-BOX64-WINEx86-TUTORIAL#2]
Hello and thanks for this easy to follow tutorial. 

I used wine64 on the Orange Pi 5 Plus (RK3588) in order to try to launch the pcsx2 emulator using the windows version but I receive this error. I use Joshua Riek's ubuntu. I have tried both X11 and wayland as well as used the /desktop parameter you suggest but I still receive the same. 

Any ideas why? 

Thank you

![Uploading IMG_20231017_224805.jpg…](https://i.imgur.com/HhRO4kd.jpg)

**Comment by neofeo** [comment]
Well, did you use box86 and box64 for rk3588? On my script it ask if rockchip kernel or mainline. Anyway. You should use aethersx2 arm64 linux build for ps2 emulation.

**Comment by neofeo** [comment]
https://www.aethersx2.com/archive/?dir=desktop/linux

**Comment by m33ts4k0z** [comment]
Thanks for the fast answer. 

Yes i did use the repos you suggested although its not needed since box86/64 both have a cmake flag for the RK3588 so even the latest version works if you compile them yourself.

AestherSx2 works really well but since it wont be getting any updates I thought of trying pcsx2 with box64.

I receive almost the same error about the display when trying to start the linux Appimage of pcsx2 as well

**Comment by neofeo** [comment]
Most probably it's  a qt library not properly wrapped on box64 as today. Double emulation it's  overkill for ps2 emulation on an rk3588 (or any arm linix device) , you have to use aethersx2.

**Comment by neofeo** [comment]
Ptitseb will be working full time from now on on box64, so development will ramp up, but again.. do not attempt thst craziness haha

**Comment by m33ts4k0z** [comment]
Actually its tripple emulation if you count pcsx2 🤣
I will make a post with the error on the box86 repo and im quite sure that if he wraps the lib properly, the linux version will work so wine wont be needed 😅

**Comment by neofeo** [comment]
Cobsider to not do it. Pcsx2 it's  by far not a priority. It's  super overkill... also, having a native solution.  Cheers

**Comment by m33ts4k0z** [comment]
Yeah you are absolutely right but the native solution we have is very limited and maintained by hacks. Of course I will be using it now but having alternatives wont hurt in the future.

Thanks again for your tutorial 😊
