### ISSUE TITLE
Cant install the script... kinda doesnt resolve connection

### ISSUE THREAD

**Issue by DarkevilPT** [neofeo/BOX86-BOX64-WINEx86-TUTORIAL#4]
![image](https://github.com/neofeo/BOX86-BOX64-WINEx86-TUTORIAL/assets/3583885/fea91019-c6c9-47ca-9396-69e05ce081b6)

**Comment by neofeo** [comment]
Boxer isn't maintained anymore

**Comment by DarkevilPT** [comment]
> Boxer isn't maintained anymore

Then whats the "best" option for steam/boxes?

(Also the error was mine I had copied the lines but as url there was a count number added to the lines thats what made the error).

**Comment by DarkevilPT** [comment]
Just archive this if its not maintained.

**Comment by neofeo** [comment]
Okay, later on.
